GET http://localhost:3000/infouser
content-type: application/json

{
    
}
###
POST http://localhost:3000/register
content-type: application/json

{
    
    "email":"test@123",
    "username":"test",
    "firstname":"test",
    "lastname":"test",
    "phone":"123",
    "password":"123"
}
###
POST http://localhost:3000/login
content-type: application/json

{
    
    
    "username":"test",
    "password":"123"
}
###
POST http://localhost:3000/home
content-type: application/json

{
    
    
    "navColor":"#101010",
    "navName":"test",
    "bgColor":"#101010"
}

###
POST http://localhost:3000/homepage
content-type: application/json

{
    
    
    "file_name":"1696355246365_Img (2).png",
    
}

###
POST http://localhost:3000/homecard
content-type: application/json

{
    
    
    "file_name":"1696355246365_Img (2).png",
    "title":"tttw",
    "detail":"rrrrr"
    
}

###
PUT  http://localhost:3000/cardEdit/1
content-type: application/json

{
    
   
    "title":"tttw",
    "detail":"rrrrr"
    
}

###
GET http://localhost:3000/userlog
Content-Type: application/json

 {
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAMTIzIiwidXNlcm5hbWUiOiJ0ZXN0IiwiZmlyc3RuYW1lIjoidGVzdCIsImxhc3RuYW1lIjoidGVzdCIsInBob25lIjoxMjMsImlkIjoyNSwiaWF0IjoxNjk2MzE0ODQwLCJleHAiOjE2OTYzMjIwNDB9.zmqwwjkVIjrWz536kxKUamV7F6FQmJTvmK0TqXiCSrs"
}

###
GET http://localhost:3000/home
Content-Type: application/json

 {
}

###
DELETE http://localhost:3000/delete_card/7
Content-Type: application/json

 {
    
}