GET http://localhost:3000/infolog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsImVtYWlsIjoidGVzdEAxMjMiLCJ1c2VybmFtZSI6InRlc3QiLCJmaXJzdG5hbWUiOiJ0ZXN0IiwibGFzdG5hbWUiOiJ0ZXN0IiwicGhvbmUiOjEyMywicm9sZV9pZCI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjk5ODY4ODA2LCJleHAiOjE2OTk4NzYwMDZ9.fSh4UWgg6N8WZnrJFy7Sz46t4t0HFxXM3b0ZXrn_dpY

###
POST http://localhost:3000/register
content-type: application/json

{
    
    "email":"Test456@gmail.com",
    "username":"Test45678",
    "firstname":"test",
    "lastname":"45678",
    "phone":"123",
    "password":"123"
}
###
POST http://localhost:3000/login
content-type: application/json

{
    
    "username":"gggg",
    "password":""
}
###
POST http://localhost:3000/payment
content-type: application/json

{
    
    
    "account_number":"101010",
    "bank_name":"test",
    "account_name":"#101010",
    "img":"1.png"
}

###
POST http://localhost:3000/room
content-type: application/json

{
    
    
    "name":"test",
    "detail":"test",
    "price":"2",
    "quantity":"2",
    "img":"1",
    "facilities_id":"1"
    
}

###
GET http://localhost:3000/info_user
content-type: application/json

{
    
    

    
}

###
PUT  http://localhost:3000/reset/password/55
content-type: application/json

{
    "password":"ss"
}

###
POST http://localhost:3000/reserve
Content-Type: application/json

 {

    "id_room":"2",
    "id_user":"3",
    "date_start":"1232132",
    "date_end":"12.00",
    "num_guests":"5",
    "status":""
}

###
POST http://localhost:3000/facilities
Content-Type: application/json

 {
    "facilities":"Hair dryer"
}

###
DELETE http://localhost:3000/delete_card/7
Content-Type: application/json

 {
    
}